---
title: "Homework_09"
author: "Hailey Cray"
date: "4/19/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
Writing the pseudocode
Step 1: sim_ano_data() and ano_model()
Step 2: calc_anova()
Step 3: summarize_output()
Step 4: graph_results()

```{r}
library(dplyr)
library(ggplot2)
```
I have data on the systolic blood pressures of n=50 total women with opioid use disorders. There are n=25 in each group: Non-Smokers and Smokers


```{r}
# Step 1: 
# ----------------------------------
# FUNCTION sim_ano_data
# description:A simulation of systolic blood pressure scores among 2 groups (each with n=25 women with opioid disorders) where one group is comprised of smokers and 1 group is comprised of non-smokers.
# inputs: the parameters for the systolic blood pressure scores 
# outputs: the random normal distribution of the systolic blood pressures
####################################
n_size = c(25,25)
n_mean = c(136,121)
n_sd =c(16.942,15.49)
n_name = c("Smokers","Non-Smokers")

sim_ano_data <- function(n_group =2,n_name = c("Smokers","Non-Smokers"),n_size= c(25,25),n_mean = c(136,121),n_sd =c(17,15)) {
# Sophie Kogut helped me with this!  
  t_group <- rep(n_name, n_size)
  
  id <- 1:50
  
  res_var <- c(rnorm(n=n_size[1], mean=n_mean[1],sd=n_sd[1]),rnorm(n=n_size[2],mean=n_mean[2],sd=n_sd[2]))
  
  ano_data <- data.frame(id,t_group, res_var)
  return(ano_data)
  
}  
ano_data2 <- sim_ano_data()

# returns the ano_data, step one in the list given in pseudocode. 

 # end of sim_ano_data
# ----------------------------------
# Step 2: 
# ----------------------------------
# FUNCTION calc_anova
# description: drawing down from above: ano_data informs the ANOVA
# inputs: data from above chunk: the individual, group (t_group) and the response variable
# outputs: ANOVA model for smokers vs nonsmokers
####################################: 
# ano_model <- aov(res_var~t_group, data=ano_data)
calc_anova <- function(ano_data=ano_data2) {
  
ano_model <- aov(res_var~t_group, data=ano_data)
# calling data from above
summary(ano_model)
 }

calc_anova()

 # end of: calc_anova
# ----------------------------------
# Step 3: 
# ----------------------------------
# FUNCTION summarize_output
# description:create summary from my ANOVA from above
# inputs: I am using my ano_model 
# outputs: I get out my F-statistic that I can use to test for significance.
####################################
output2 <- calc_anova()
summarize_output <- function(output=output2, ano_data=ano_data2) {
  p <- summary(output)
  means <- aggregate (res_var~t_group, data=ano_data, FUN=mean)
  ano_sum <- list(Fval = as.numeric(unlist(output)[7]),
                  probF=as.numeric(unlist(output)[9]))
  summary_anova <- c(ano_sum, means)
  return(summary_anova)

# Sophie helped me write this section of script and I replaced with my own data and parameters.

} 
summarize_output()
# end of summarize_output
# ----------------------------------
# Step 4: 
# ----------------------------------
# FUNCTION graph_results
# description:description
# inputs: input_description
# outputs: output_description
####################################
graph_results <- function(data=ano_data2) {
ano_plot <- ggplot(data=data,
                   aes(x=t_group,
                       y=res_var,
                       fill=t_group)) +
                      geom_boxplot()
print(ano_plot)
}

graph_results()
 # end of graph_results
# ----------------------------------
# ANOVA
ano_model <- aov(res_var~t_group, data=ano_data2)
# res_var as a function of ano_data
print(ano_model)
print(summary(ano_model))
z <- summary(ano_model)
str(z)
aggregate(res_var~t_group,data=ano_data2,FUN=mean)
print(z)
```

Part 2. A new function
```{r}
# Trying a new graph out
####################################
sim_ano_data <- function(n_group =2, # non-smokers and smokers
                         n_name = c("Smokers","Non-Smokers"),
                         n_size= c(25,25),
                         n_mean = c(136,121),
                         n_sd =c(16.942,15.49)) {
  t_group <- rep(n_name, n_size)
  id <- 1:(sum(n_size))
  
  res_var <- c(rnorm(n=n_size[1], mean = n_mean[1], sd=n_sd[1]),
               rnorm(n=n_size[2], mean=n_mean[2], sd=n_sd[2]))
  ano_data <- data.frame(id, t_group, res_var)
  return(ano_data)
} 
smoker_data <- sim_ano_data()

matrix_bp <- data.matrix(smoker_data)
print(matrix_bp)
smoker_dotplot <- ggplot(smoker_data, aes(x=t_group, y=res_var, fill=t_group)) + 
  geom_dotplot(binaxis ="y", stackdir = "center", stackratio=1.5, dotsize=1.2) + labs(title="Plot of Systolic Blood Pressure of Women with OUD by Smoking Status at MAT Intake",x="Smoking Status", y = "Systolic Blood Pressure in mm Hg")

print(smoker_dotplot)
# from stackoverflow
```


