---
title: "HW 3"
author: "Hailey Cray"
date: "1/29/2020"
output: html_document
---
Problem 1: 


```
Find: \s{2,} Replace: ,
```


> I found the 2 spaces between each of the words, (i.e. "First String" and "Second"). Then replaced with a common to remove all spaces between them and sub a comma in. 


Problem 2: 


```
Find: (\w+), (\w+), (\w+ \w+\s*\w+$) Replace: \2 \1 (\3) 
```


> I translated the lines of the list into BBedit's language and indicated the end of the line using a $, then instructed the program to reorder it using the numbers assigned to the words and then placed the third word in parentheses so that it would be bracketed. 


Problem 3 and 4: 


```
Step 1: Find: p3space Replace: p3/n to place all on their own lines. Step 2: Find: (000\w)( \w* \w*\s*\w*\s*\w*)(\.mp3) Replace: \2_\1\3 
```


> I did this in two steps. First, I placed all the songs on their own individual lines using the /n command. Then I translated the song titles by first listing thir number beginning with three zeroes and bracketing that, then translating the title and bracketing it as well. Finally, the .mp3 suffix was also bracketed. Then it was reordered using the numbers assigned to each bracketed set and the underscore added in. 

Problem 5 and 6:


```
Step 1: Find: ^(\w)\w+, Replace: \1_\2
Step 2: Find: ,\d+.\d, Replace: ,
Step 3: Find: (_\w{4})\w+ Replace: \1
```


> I couldn't do this one in one step and figured out a three-step process that made sense to me. First, I defined each on their own line and added the underscore. Then I removed the decimal number and replaced it with a comma, which gave me the answer to #5. Then in the third step which gave the answer for #6, I defined the first four letrers of the word after the underscore using curly brackets, then encapsulated it in parentheses to define it as word one. I then followed up with the \w+ command and replaced as \1. 

Problem 7: 


```
Find: ^(\w{3})\w+,(\w{3})\w+,(\d+.\d),(\d+)
Replace: \1\2, \4, \3
```


> For this one, I first defined all on their own lines with the ^ and then translated. I then specified to keep and fuse the first three word characters using the curly brackets. The parentheses defined each word into words 1-4 and then reordered them to replace. 
